export const Users = [
    {
      id:1,
      profilePicture: "https://thumbs.dreamstime.com/b/portrait-smiling-attractive-cheerful-young-man-face-human-facial-emotions-expressions-close-up-happy-having-fun-joy-153222193.jpg",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "https://www.shutterstock.com/shutterstock/photos/2200214153/display_1500/stock-photo-confident-rich-eastern-indian-business-man-executive-standing-in-modern-big-city-looking-and-2200214153.jpg",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "https://previews.123rf.com/images/olegdudko/olegdudko1507/olegdudko150702286/42120239-men-human-face-smiling.jpg",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "https://c8.alamy.com/comp/W3KFFR/close-up-portrait-of-handsome-young-male-in-his-twenties-with-happy-face-smiling-and-making-cheerful-gestures-at-the-camera-positive-human-facial-exp-W3KFFR.jpg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "https://thumbs.dreamstime.com/b/portrait-attractive-cheerful-young-man-smiling-happy-face-human-expressions-emotions-model-beautiful-smile-handsome-154272095.jpg",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "https://as2.ftcdn.net/v2/jpg/02/67/99/59/1000_F_267995900_qg8jfTCHvCijDkXC5HOlPBK0pZ0i0dlh.jpg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "https://www.shutterstock.com/image-photo/close-photo-charming-guy-entrepreneur-260nw-1531460651.jpg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "https://www.diariojuridico.com/wp-content/uploads/2022/04/mujeres-empleo-jovenes-diariojuridico.jpg",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "https://media.istockphoto.com/id/1139493497/photo/ive-got-no-worries.jpg?s=612x612&w=0&k=20&c=JfVFxlHxhD9K1z3FIx_DnQStHPDf8-72uChdopjCX8Y=",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "https://media.istockphoto.com/id/1351047032/photo/portrait-of-a-young-adult-woman-against-a-white-background.jpg?s=612x612&w=0&k=20&c=vsT0f9sG_ClTkqjgFN1zG2MmVqUw0HwvcBvrhm9FOmw=",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "https://www.shutterstock.com/image-photo/handsome-smiling-young-man-folded-260nw-2069457431.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "https://assets.weforum.org/article/image/XaHpf_z51huQS_JPHs-jkPhBp0dLlxFJwt-sPLpGJB0.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "https://i0.wp.com/dungeonsanddragonsfan.com/wp-content/uploads/2024/04/all-dnd-classes-5e-druid.png?resize=800%2C450&ssl=1",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "https://dungeonsanddragonsfan.com/wp-content/uploads/2024/05/druid-dnd-5e-class-guide-3.png",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "https://www.depts.ttu.edu/hs/images/hs-building-updated.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "https://www.cmich.edu/images/default-source/colleges/education-and-human-services/college/2021415_cmucampus_capandgown-students_001_834-x-350e9ef2a02-967b-4a2f-9ade-4094d419f914.png?Status=Master&sfvrsn=6ae2930c_7",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/7.jpeghttps://www.nga.org/wp-content/uploads/2022/02/many-children-happy-family-group-and-sunrise-sky-vector-20180282.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "https://www.shutterstock.com/image-photo/university-maryland-260nw-659670.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "#Its an awesom day",
      photo: "https://louisville.edu/artsandsciences/advising/images/PeerAdvidors2018.jpg/@@images/48d638fe-5fd1-4fe1-9b4e-4b13ab1587cd.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "https://www.unf.edu/newsroom/2024/images/Stultz-Thumbnail.png",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];